version: "3"
services:
  new_db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - new_db_data:/var/lib/mysql

  directus:
    # 11.3.2
    # 11.5.1
    image: directus/directus:11.5.1
    ports:
      - "8055:8055"
    depends_on:
      - new_db
    environment:
      SECRET: ${SECRET}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DB_CLIENT: ${DB_CLIENT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      STORAGE_LOCATIONS: ${STORAGE_LOCATIONS}
      STORAGE_CLOUDINARY_DRIVER: ${STORAGE_CLOUDINARY_DRIVER}
      STORAGE_CLOUDINARY_CLOUD_NAME: ${STORAGE_CLOUDINARY_CLOUD_NAME}
      STORAGE_CLOUDINARY_API_KEY: ${STORAGE_CLOUDINARY_API_KEY}
      STORAGE_CLOUDINARY_API_SECRET: ${STORAGE_CLOUDINARY_API_SECRET}
      STORAGE_CLOUDINARY_ACCESS_MODE: ${STORAGE_CLOUDINARY_ACCESS_MODE}
      WEBSOCKETS_ENABLED: ${WEBSOCKETS_ENABLED}
      HOST: ${HOST}

volumes:
  new_db_data:
